### ISSUE TITLE
Green arrow from Duskwood to Deadwind Pass missing

### ISSUE THREAD

**Issue by alasmo** [leatrix/leatrix-maps-classic#13]
The green arrow from Duskwood to Deadwind Pass is missing.

Also, should the arrow from Searing Gorge to Blackrock Mountain not point north rather than west?

**Comment by leatrix** [comment]
Many thanks, alasmo.  The Duskwood to Deadwind Pass arrow is added in the latest alpha.  The arrow from Burning Steppes (think you meant that?) to Blackrock Mountain is pointing west because that's the direction your character is facing when you're at that location.  However, I've changed it to northwest so it's more obvious where the arrow is pointing towards.
