### ISSUE TITLE
Maw not showing full map discovered with the setting on to remove all unexplored spots

### ISSUE THREAD

**Issue by zeenk** [leatrix/leatrix-maps-classic#14]
https://imgur.com/a/iw8rRSr <- (only this addon enabled screenshot)

**Comment by leatrix** [comment]
Are you sure only LTM is enabled?  It looks like you might have missed one or two. 
 Can you check?  It's likely that the revealed map is actually just what you have explored already and LTM is not revealing anything.  This is usually caused by the addon not loading correctly due to a conflict with another addon.

**Comment by zeenk** [comment]
> Are you sure only LTM is enabled? It looks like you might have missed one or two. Can you check? It's likely that the revealed map is actually just what you have explored already and LTM is not revealing anything. This is usually caused by the addon not loading correctly due to a conflict with another addon.

Here's another screenshot I just took on another character, I clicked disable all in addon menu and only enable leatrix maps and getting same results, but for some reason it's only happening in maw, no other zone is having that issue from what I've seen so far.

**Comment by leatrix** [comment]
Thank you.  Another reason this could occur is if the game has multiple maps for a single zone (for phasing).  Do you have alts you can check this on?

Open up the world map to The Maw where you are experiencing this issue and enter /ltp map into chat (with the map open).  Some numbers and the zone name will be printed in chat.  What does it say (or just post another screenshot)?

**Comment by zeenk** [comment]
/ltp map is not working, no valid command with only leatrix maps enabled

**Comment by zeenk** [comment]
Had to enable leatrix plus aswell for the command to work. Here is the chat print screenshot on main char with everything explored & another alt with only some explored. https://imgur.com/a/tt6iALK

**Comment by leatrix** [comment]
Sorry yes, it's a Leatrix Plus command.  I get so used to using them both together I forget they're different addons sometimes.  So the numbers are the same but none of your alts can see the whole map.  It's showing for your main char because your main char has actually explored everything so LTM isn't revealing anything for that character.  And you say that it's only affecting that one zone with no other addons enabled.

If it was affecting all zones, I would say click the little configuration button next to the 'Show unexplored areas' setting and click the reset button to reset the tint (since it's possible to set the tint in such a way that it makes it appear that the reveal setting isn't working).  Worth a shot to try it though?

**Comment by zeenk** [comment]
https://imgur.com/a/jqPgq4S Yep, looks like it's broken in maw for some reason, it's showing tinted unexplored in other zones when I zoom out and check other parts of the world map.

**Comment by leatrix** [comment]
Ah yes.  I see it now.  The map data for those numbers is missing so this affects everyone but strangely, nobody has ever reported it until you did.  I'll add the missing map data and update you here soon.

**Comment by zeenk** [comment]
I also tried the /ltp map command in the "maw intro phase" version and is giving me some different numbers, maybe useful to you? idk :P https://imgur.com/a/E9v1Pid

**Comment by leatrix** [comment]
Yes, that's the reason the map data is missing - there are two maps for intro and main but only one map was included in LTM.  Strangely, nobody ever reported that the other map was missing.  I added the missing map data in 9.1.33.alpha.2 and credited you in the change log for being the first person ever (since Shadowlands began...) to report the missing map data.

https://www.curseforge.com/wow/addons/leatrix-maps/files/all

I also added the map command to LTM so you can use **/ltm map** now without having to use LTP (though you should use LTP because it's awesome).

On it's own, if the world map is not open, /ltm map will show your character's map ID (for the zone that your character is in) along with the art ID for that map.

If the map is open, it will show the map ID and art ID for the currently showing map.

If the map is open and you supply a map ID with the command (i.e. /ltm map 1543), the world map will show the map for that ID.  So /ltp map 37 will show Elwynn Forest.

And if you use LTP, you can click Media > Zones > Elwynn Forest and listen to the music of Elwynn Forest while you fight off the evil marauders of the Maw.  Heaven.

**Comment by zeenk** [comment]
https://imgur.com/a/1G0zimK Works now, thank you :) 👍
