### ISSUE TITLE
Group / raid member not on world map 

### ISSUE THREAD

**Issue by Gourdin** [leatrix/leatrix-maps-classic#7]
Hey,

I don't know if it was a recent update, but group / raid members don't seem to appears on the world map anymore, without LMP everything is working fine and with LMP I don't see anybody (but still see them on the minimap if it can help)

**Comment by leatrix** [comment]
Restart your game client.  Is this for Burning Crusade Classic?

**Comment by Gourdin** [comment]
Yeah it's in tbc classic, restart client doesn't work, delete WTF files don't either. Same issue with all accounts, it was working fine last week... Weird !

**Comment by leatrix** [comment]
This issue tracker is for World of Warcraft Classic.
Burning Crusade Classic for the issue you're raising is here:
https://github.com/leatrix/leatrix-maps-bcc/issues/18

The group icons are missing because Blizzard removed the built-in group icon texture.  So I added the texture file to the addon folder.  You need the latest version followed by a full game client restart to use the new texture file (a simple reload doesn't work for BCC).

Download and install the latest version of Leatrix Maps for Burning Crusade Classic (currently 2.5.41) from here:
https://www.curseforge.com/wow/addons/leatrix-maps-bcc/files/all

Then close your Wow client completely and relaunch it (a reload is not sufficient).

If you have any further issues, please use the issue above.
